[tool.poetry]
name = "pvserver"
version = "4.0.2"
description = "RAS Python backend. It mainly manages connections with PVs, through a websocket connection, authentication, authorization, plus other optional functionalities."
authors = ["React Automation Studio Team https://github.com/React-Automation-Studio/React-Automation-Studio/discussions"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/React-Automation-Studio/React-Automation-Studio"

[tool.poetry.dependencies]
python = "3.8.7"
Flask = "2.1.2"
pyepics = "3.4.3"
gevent = "21.12.0"
bcrypt = "3.2.2"
python-ldap = "3.4.0"
pymongo = "4.1.1"
python-dotenv = "0.20.0"
Flask-Cors = "3.0.10"
Flask-SocketIO = "5.1.2"
PyJWT = "1.7.1"
google-api-python-client = "2.73.0"
gevent-websocket = "0.10.1"

[tool.poetry.dev-dependencies]
black = "22.3.0"
pytest = "7.1.2"

[build-system]
requires = ["poetry-core=1.0.8"]
build-backend = "poetry.core.masonry.api"
